export const COLOR_THEME = {
  background: {
    primary: "bg-blue-800",
    primaryReverse: "bg-blue-100",
    primaryHover: "hover:bg-blue-700",
    primaryFocus: "focus:bg-blue-700",
    primaryActive: "active:bg-blue-700",
    secondary: "bg-sky-500",
    secondaryReverse: "bg-sky-100",
    secondaryHover: "hover:bg-sky-400",
    secondaryFocus: "focus:bg-sky-400",
    secondaryActive: "active:bg-sky-400",
    tertiary: "bg-white",
    tertiaryReverse: "bg-black",
    tertiaryHover: "hover:bg-slate-100",
    tertiaryFocus: "focus:bg-slate-100",
    tertiaryActive: "active:bg-slate-100",
  },
  border: {
    primary: "border-blue-800",
    primaryReverse: "border-blue-100",
    primaryHover: "hover:border-blue-700",
    primaryFocus: "focus:border-blue-700",
    primaryActive: "active:border-blue-700",
    secondary: "border-sky-500",
    secondaryReverse: "border-sky-100",
    secondaryHover: "hover:border-sky-400",
    secondaryFocus: "focus:border-sky-400",
    secondaryActive: "active:border-sky-400",
    tertiary: "border-white",
    tertiaryReverse: "border-black",
    tertiaryHover: "hover:border-slate-300",
    tertiaryFocus: "focus:border-slate-300",
    tertiaryActive: "active:border-slate-300",
  },
  text: {
    primary: "text-white",
    primaryReverse: "text-black",
    primaryHover: "hover:text-gray-100",
    primaryFocus: "focus:text-gray-100",
    primaryActive: "active:text-gray-100",
    secondary: "text-white",
    secondaryReverse: "text-black",
    secondaryHover: "hover:text-gray-100",
    secondaryFocus: "focus:text-gray-100",
    secondaryActive: "active:text-gray-100",
    tertiary: "text-gray-950",
    tertiaryReverse: "text-gray-400",
    tertiaryHover: "hover:text-gray-700",
    tertiaryFocus: "focus:text-gray-700",
    tertiaryActive: "active:text-gray-700",
  },
  outline: {
    primaryFocusVisible: "focus-visible:outline-sky-800",
    secondaryFocusVisible: "focus-visible:outline-sky-400",
    tertiaryFocusVisible: "focus-visible:outline-slate-100",
  },
  ring: {
    primaryFocus: "focus:ring-blug-700",
    secondaryFocus: "focus:ring-sky-400",
    tertiaryFocus: "focus:ring-slate-300",
  },
};
